name: Render documents with rmarkdown-action
on: 
  push:
    branches: 
      - main
    paths:
      - "./Prácticafinal/*.rmd"
jobs:
  render_documents:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        document_type: [pdf_document, html_document]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Render document
        uses: happyRip/rmarkdown-action@v1.1
        with:
          input_file: "./Prácticafinal/práctica.rmd"
          output_format: ${{ matrix.document_type }}
  commit_files:
    needs: [render_document_pdf, render_document_html]
    runs-on: ubuntu-latest
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}